### ISSUE TITLE
Activate reserve list talks as confirmed

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#138]
When selecting a reserve list speaker, we usually talk to the reserve list speaker first, before activating the talk. Which means we already know that the speaker can present the talk, and the dance "reserve list" -> "pending" -> "confirmed" is not (always) necessary.

Offer an additional option to directly activate the talk.

**Comment by mhagander** [comment]
The transition from "reserve list" -> "confirmed" (r rather, "approved" as it's called in the system) is already possible, and has been allowed since the transition validation was implemented in 7e82205d7. It's also documented in the state transition diagram.
