### ISSUE TITLE
Support higher resolution speaker photos

### ISSUE THREAD

**Issue by mhagander** [pgeu/pgeu-system#15]
Right now speaker photos are required to be 128x128 pixels, which is abysmal.

We should support a larger photo, and automatically generate a thumbnail at 128x128 when uploaded. Possibly support both high/medium/low resolution, where low would be the 128x128.

So we want to store at least 2, or maybe 3, different resolutions of the photo in the db, so we can pick up the correct one. Have the speaker upload the highest resolution one and generate the lower ones automatically (never request the speaker to upload multiple versions).

**Comment by dlangille** [comment]
Please consider non-JPG, such as PNG

**Comment by Saurav-Shrivastav** [comment]
The solution that I've thought of is -
Override the save() method of the Speaker model and modify the image to the required 128*128 pixel resolution and then save it.

What do you think @mhagander ?

**Comment by mhagander** [comment]
I think we'd want the resizing process to run "closer to the user", so we can give nicer error messages if//when something goes wrong. It should probably go in the form or view to handle that?
