### ISSUE TITLE
URL field for slides in admin interface is too short

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#151]
Trying to add the FOSDEM link for this talk:

https://www.postgresql.eu/events/admin/fosdem2024/sessions/4978/

And the FOSDEM link is:

https://fosdem.org/2024/schedule/event/fosdem-2024-3600-isolation-levels-and-mvcc-in-sql-databases-a-technical-comparative-study/

This addition is rejected because the URL is too long, yet the URL is valid.

**Comment by andreasscherbaum** [comment]
Another issue:

https://www.postgresql.eu/events/admin/fosdem2024/sessions/5209/

Link:

https://fosdem.org/2024/schedule/event/fosdem-2024-3601-reducing-costs-and-improving-performance-with-data-modeling-in-postgres/

**Comment by andreasscherbaum** [comment]
Another one:

https://www.postgresql.eu/events/admin/fosdem2024/sessions/5002/

https://fosdem.org/2024/schedule/event/fosdem-2024-3602-clustering-in-postgresql-because-one-database-server-is-never-enough-and-neither-is-two-/

**Comment by mhagander** [comment]
This only applies to the admin interface, and not when speakers upload their own slides. The field itself seems fine, but clearly something is off in the admin interface.
