### ISSUE TITLE
Name tags are incorrectly recapitalized

### ISSUE THREAD

**Issue by MMeent** [pgeu/pgeu-system#160]
E.g. the input of (correct)
```
Matthias
van de Meent
```
is recapitalized to (incorrect)
```
Matthias
Van de meent
```
in name tag output.

Dutch casing rules _can_ add capitalization to the 'v' of the 'van de' particles here, but never allow decapitalization for the 'm' of the last name proper.

**Comment by mhagander** [comment]
This capitalization is not done by the system. It's done as part of the badge design for the specific conference you attended. The system itself doesn't touch the capitalization at all.

(I believe it was discussed for the particular conference and the conclusion there was that capitalizing it this way fixed more than it broke but that it did break some)

**Comment by mhagander** [comment]
If there's code out somewhere that knows how to parse names from most major cultures and languages and capitalize with that knowledge we could potentially incorporate that in the code to be available, but without that there isn't anything to do at the system level.
