### ISSUE TITLE
Improve error message when Registration is not yet open

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#18]
The website shows a confusing message when the registration is not (yet) open.

Improve the error message, based on if the conference is in the future or in the past.

**Comment by mhagander** [comment]
Which error message and where?

**Comment by andreasscherbaum** [comment]
![pgconfde2020](https://user-images.githubusercontent.com/1191463/73064124-c809db00-3ea0-11ea-8222-2d9660437aff.jpg)

**Comment by mhagander** [comment]
I fail to see what's unclear about "Registration for <conference> is closed", when in fact, registration for <conference> is closed.

**Comment by dlangille** [comment]
"Closed" implies it was previously open.

When compared with "Will open soon" or "Is not yet open", it is easier to conclude that you have not yet missed the registration period.
