### ISSUE TITLE
Archive emails sent using cross-conference email

### ISSUE THREAD

**Issue by mhagander** [pgeu/pgeu-system#20]
We currently archive emails sent to attendees and sponsors, but not when using the cross-conference sending. Doing so would be useful, both for a future bounce-matching but also for any kind of debugging of "why did *x* receive this" or "why did *y* not receive this".

Should store both the email itself, and the selection criteria that made the attendees included.

**Comment by andreasscherbaum** [comment]
Should also include a reference (hash) which is included in the email, making it possible to track back the bounced email to a sent email.
