### ISSUE TITLE
Functionality of the "Discard" button in the Twitter queue is unclear

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#22]
The Twitter site has 4 buttons: "Reply", "Discard", "Retweet" and "View on twitter".
It is unclear what exactly will be discarded when the "Discard" button is hit.

Either make the button label more precise, or have an on-hover description.

**Comment by mhagander** [comment]
Would a on-hover really work? The primary interface for this is on a mobile touchscreen, which doesn't actually have hover?

Because if it did, it would probably be easier to just copy the message that's in the confirmation message that you get after you click the button?

**Comment by andreasscherbaum** [comment]
That's why I mentioned two options, one of them being "make the label more precise".
"Discard" throws something away, or deletes something. That's not encouraging for users who never used that interface.

**Comment by andreasscherbaum** [comment]
I'm looking over the code for this, and the non-existent help for regular users (there is a bit of help for the admin page, but it does not specifically mention the resulting action either.

My proposal is to rename this button to "Acknowledge".

**Comment by mhagander** [comment]
Hmm. I'm not sure I like that one either.. Maybe "Ignore"?

**Comment by andreasscherbaum** [comment]
I feel like this should be answered by one of those UI A/B design polls ;-)
Because you and I know the meaning of the button (well, you knew all the time, and I know now).

**Comment by mhagander** [comment]
Ran into another similar interface for a completely different thing, that gave me an idea. How about "Dismiss"?

**Comment by andreasscherbaum** [comment]
Would work for me.

My questionnaire among a few other people also did not come up with an useful result. People either already worked with the interface and knew the thing by then, or never worked with it and didn't know what to do there.

**Comment by andreasscherbaum** [comment]
Fixed in https://github.com/pgeu/pgeu-system/commit/09421db0316360b20e1022fbaf12a91c13defaf5
