### ISSUE TITLE
Email for volunteer changes

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#24]
When a volunteer changes the status of an item (sign up or remove), there should be an email to the volunteer admins. This email should include links to confirm the change (which otherwise needs to be done manually).

**Comment by mhagander** [comment]
Since volunteers can't remove a confirmed session without emailing the organizer, there is nothing to notify for there.

There *is*, however, a point in sending a notification when the volunteer confirms an item (and when signed up as suggested), so it ends up being two notifications regardless :)
