### ISSUE TITLE
Enhance "copy talk" feature

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#26]
When copying a talk to another conference, include the status of the talk in the original conference.

**Comment by mhagander** [comment]
This would leave an opening for any speaker accepted at one conference to magically be accepted on another one by just copying their talk there. This seems like a seriously bad idea.

**Comment by andreasscherbaum** [comment]
Can we have something like "system notes", which can't be changed by the speaker?
And move things like "copied from conference xyz" into this field?
