### ISSUE TITLE
dev_setup.sh uses deprecated option

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [pgeu/pgeu-system#65]
Line number 29 in [this](https://github.com/pgeu/pgeu-system/blob/master/tools/devsetup/dev_setup.sh) file uses the argument `--no-site-packages` with virtualenv, which was removed  for virtualenv>=20.

**Comment by andreasscherbaum** [comment]
This [documentation](https://virtualenv.pypa.io/en/legacy/reference.html) says:

    Not having access to global site-packages is now the default behavior.
Seems like it is safe to remove the flag - for newer version.
I can't see when it was deprecated, and which virtualenv versions still depend on this flag.

**Comment by Saurav-Shrivastav** [comment]
@andreasscherbaum It was removed when the major version 20 was released for virtualenv.

**Comment by andreasscherbaum** [comment]
@Saurav-Shrivastav I get that point, but my question is different:
* Which version deprecated this flag?
* And since it says that "no access is **now** the default behavior", which version changed that?
Because every version before that still depends on the old flag, and behavior.
Not everyone is running version 20 already.

**Comment by Saurav-Shrivastav** [comment]
I found this - https://virtualenv.pypa.io/en/legacy/changes.html#v1-7-2011-11-30 (see point 3). So, the behaviour was made default in 2011 (v17). 
I can't exactly find the version when it was deprecated, they haven't mentioned it in their change-logs. 

I also found this statement in one of the issues - 
> Hello, you can still find the legacy (v16) documentation here https://virtualenv.pypa.io/en/legacy/reference.html. v20 aimes to be cli compatible with v16 baring some flags that have been deprecated for years now. https://virtualenv.pypa.io/en/legacy/reference.html#cmdoption-no-site-packages is one of this, so we've dropped it during the migration to the new major version. We're sorry if this caused issues for you, you're right we should have mentioned it somewhere in our release changelog though.

**Comment by mhagander** [comment]
Agreed, with this being the default for so long, we should just get rid of it. Thanks for doing the research!
