### ISSUE TITLE
Timestamps on the volunteer schedule should not show the timezone

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#69]
The volunteer schedule system shows timestamps like this:
```
2021-12-02 09:45:00-05:00 - 2021-12-02 11:30:00-05:00
```

This is not helpful, because the conference itself has a timezone set, and any time should be related to that timezone.
Showing raw timestamp information right from the database is confusing.

**Comment by mhagander** [comment]
Where exactly is this? If I just go into the volunteer schedule page, it shows the hours and minutes only, and no date and timezone. E.g. like this:

![image](https://user-images.githubusercontent.com/174657/152651067-956a5504-3ede-46bb-ab8e-321ae96d2c54.png)

**Comment by andreasscherbaum** [comment]
When you edit the volunteer slots.
![image](https://user-images.githubusercontent.com/1191463/152651815-8bd2c5ab-86f7-49cb-93ca-6ca9f3ea3af3.png)

**Comment by mhagander** [comment]
Ah, the slots, not the schedule itself. Gotcha, I see it now!
