### ISSUE TITLE
Padding option for sponsor images in the sidebar

### ISSUE THREAD

**Issue by danielwestermann** [pgeu/pgeu-system#71]
Hi,

it would be great to have a padding option in the sponsor section of context.json. The workaround currently is to adjust base.html like this:

`<li><a href="{% if s.hasdescription %}{{ link("sponsors/#") }}{{ c.name | slugify }}{% else %}{{ c.url }}{% endif %}"><img src="{{ media("img/logos/sidebar/" + c.img) }}" alt="{{ c.name }}" style="padding:10px;"/></a></li>`

Without padding it does not look really nice. Or do I miss something and it is already there?

Regards
Daniel

**Comment by xocolatl** [comment]
You are already writing your own css, why not put it in there?

``` .css
aside.sponsors img {
    padding: 10px;
}
```

**Comment by mhagander** [comment]
I agree with @xocolatl that this is something that should be solved in CSS. Doing inline styles like that is bad.

But even more to the point, `context.json` is something you set up locally, and what fields are or are not included there is not part of `pgeu-system`. So if you do want to add padding information in `context.json` you can just go ahead and do that. You can put anything you want there.
