### ISSUE TITLE
Needs a "no t-shirt after x days before conference" option

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#79]
pgconf.de 2022 currently runs into a luxury position: we will exceed the projected number of attendees. The hotel allows us to go higher with the number. If we do that, it means we will not have a t-shirt for everyone.

Right now there is no option to stop people from signing up without a t-shirt.

**Comment by xocolatl** [comment]
We had the same problem for pgDay Paris.  The way I dealt with it there was to display that the preferred shirt size may not be available after <order date>.  I planned to formalize this in the system which would also prevent people from changing their shirt size after that date.

**Comment by danielgustafsson** [comment]
Should each option have a time range associated such that they can be set within the range, and will get a default value when outside the range?

**Comment by xocolatl** [comment]
In our case, we order an extrapolated number of shirts, so we still want late registrants to be able to choose their preferred size, we just want them to know that they might not get it.

**Comment by andreasscherbaum** [comment]
We did the same for Germany, although as I said, we are in a luxury position now: we exceeded our projection by quite a bit, and it's still a week until the conference.

**Comment by xocolatl** [comment]
Okay, but what is lacking by just having on the registration form that they are not guaranteed to get the shirt they want?

Maybe we could have a place to input how many of each size there are, and then the system could refuse based on that?

**Comment by andreasscherbaum** [comment]
Sounds complicated to handle, and makes changing sizes more problematic.
I'd rather just automatically disable the t-shirt option at some point and if we have some left they can pick one up in their size after the conference ends.

**Comment by danielgustafsson** [comment]
> On 9 May 2022, at 01:40, Vik Fearing ***@***.***> wrote:

> Maybe we could have a place to input how many of each size there are, and then the system could refuse based on that?

While somewhat offtopic, but.. If I register for a conference *while registration is open*, and I'm told I can't get the benefits that other attendees who also registered while registration was open gets, I wouldn't be entirely amused by that. But, thats beside the point of the discussion here.

**Comment by andreasscherbaum** [comment]
> I'm told I can't get the benefits that other attendees who also registered while registration was open gets

The consequence of this is to close the registration once we run out of t-shirts.
I think it's reasonable to explain that people who register very late might face a minor issue, especially when the conference makes an effort to even accommodate more people.

**Comment by xocolatl** [comment]
That is why the registration form shows the date after which the benefit is not guaranteed. The alternative is too close registration weeks before the event.

**Comment by mhagander** [comment]
Yeah, I think being clear that it's a preference and not a guarantee is the way to go in general. 

If we want to make it a guarantee we already have a separate system for that -- make it an additional option with a limited number (the limit can be set at a later date) but with zero cost.

Just removing the field from the regform is going to cause all sorts of weird side-effects for people who have already filled it out, as it will no longer show on their dashboard etc. And special-casing just *one* field on the regform for this seems like a terrible idea.

So my suggestion is we close this issue with the comment that either (1) make it a not-guaranteed option, or (2) use the additional options  system.

**Comment by mhagander** [comment]
Closing this one since there's been no further activity and we have a suggestion for how to solve the problem.

**Comment by andreasscherbaum** [comment]
And as usual, people don't read what's written in the registration. This year we had a rather large jump of registrations (around 70) in the last 3 weeks of the conference, so we were about 50 shirt short. And people expected a shirt, because they have been able to select a shirt size when registering.

While technically it is true that the registration says "not guaranteed", it nevertheless leaves a lot to deal with when people arrive at the conference.
