### ISSUE TITLE
Shorten timestamps in reports

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#80]
The attendee report does not need to print the exact timestamp, down to the millisecond and time zone, most of the time.

Shorten the timestamp to either days or day + time (hour/minute), maybe make this a checkbox.

**Comment by mhagander** [comment]
Not sure we need to make it configurable -- but definitely stripping out millisecond and timezone we should do everywhere. Perhaps doing that will make it "small enough" that we don't need to add complexity beyond that.

**Comment by mhagander** [comment]
Let's start with just truncating it down to the minute level, and see  after some real-world usage if that's enough or  if we really need to also be able to truncate it to date only.

**Comment by mhagander** [comment]
Fixed in 8b30c7ce
