### ISSUE TITLE
Add distinct number of speakers to session status report

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#82]
The session status report during the CfP phase only shows the total number of submissions. It would be nice to also see the distinct number of speakers - which will give a nice overview how many talks can be accepted if every speaker gets one talk.

**Comment by mhagander** [comment]
I'm not sure what this even means -- can you provide an example of what the output would look like? (Or even better, the SQL that would produce it since this report is just a plain SQL)

**Comment by andreasscherbaum** [comment]
This [report](https://www.postgresql.eu/events/admin/pgconfeu2022/reports/simple/?report=sessionstatus) shows only the number of sessions, but does not show how many distinct speakers submitted talks. That's a useful information to have during the CfP phase.

**Comment by mhagander** [comment]
Saying the same thing as the original report doesn't help me figure out exactly which number you mean :) Per group? Per status? Per what?

So again, if you can provide an example of how it would look with the data you're looking for, it would make it a lot easier :)
