### ISSUE TITLE
Send list of sponsor emails when a new sponsor signs up

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#87]
When a new sponsor signs up, they can see all previously sent messages to this sponsor level.

Reality is: no one looks into that.

Once the sponsor is confirmed, the system can re-send the messages to this new sponsor, placing the old messages squarely in their inbox to work with.

**Comment by mhagander** [comment]
Per discussion this is a bad idea as a flood of email like that can trigger spam filters. What we should do instead is send a list of the previous emails (with links) in addition to the welcome email (for a total of 2 emails, which should not be enough to trigger spam filters).
