### ISSUE TITLE
Edit speaker in django admin is broken

### ISSUE THREAD

**Issue by mhagander** [pgeu/pgeu-system#9]
This got broken with the change of how images are handled.

Normally this view is not used so it's not urgent, but should definitely be fixed.

**Comment by mhagander** [comment]
That is, editing a speaker through the regular /admin/ interface works fine.

**Comment by andreasscherbaum** [comment]
There is - it seems - no way except the Django admin to extract a speaker's picture.

**Comment by mhagander** [comment]
Not sure what you mean by extract the speakers picture? Just bring up the spekaer record and do a save as on the image?

**Comment by andreasscherbaum** [comment]
The website throws the error exactly when I want to bring up the speaker record ...

**Comment by mhagander** [comment]
We are probably talking about two different things then. Because it's when using the normal /admin/ interface that it *works*, perfectly fine. It's only when using the django admin it doesn't work.
