### ISSUE TITLE
Allow scheduled attendee and sponsor emails

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#90]
Right now it's only possible to enter an email and send it instantly.

Scheduled messages allow to prepare emails in advance, and use the system to send them at convenient times - without anyone being around at the exact time.

**Comment by mhagander** [comment]
This definitely is something we want.

But it should be done as part of some centralization of the email handling that we have today, which will make it closely related to #74 and #53 (and possibly more). So while we want it, it definitely does not qualify as a "good first issue" as the current setup is a bit too messy to make it that.
