### ISSUE TITLE
Allow attendees to specify their profession

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#91]
We can allow attendees to specify their profession, from a pre-defined list of options.
This list can come with additional benefits (or maybe this should be a separate checkbox): let other attendees know.

We got a couple questions about journalists at the event, would be nice if attendees can signal that they are a journalist and this information can be shared.

**Comment by mhagander** [comment]
I can agree with adding a field for this

I *strongly* disagree with a pre-defined list of systems. That just means that almost all the data we get is pointless. If you look at pretty much any other system where there is such as list, there is extremely seldom a matching entry -- or there is more than one matching entry -- for most people. Which means you get data that is for practical purposes useless.

So +1 for adding the field (just like other reg fields like nicks and twitter and what not, make it configurable per conference of course), but -10 for making it a predefined list.

**Comment by andreasscherbaum** [comment]
The idea behind a pre-defined list is that we can then go in and do more specific work on it. The use case I had/have is "journalists", which allow their address to be sent upfront to others asking for this information (especially sponsors).

I agree that it's a first thought and might need better discussion how to solve this. A free text list will not help us much.

**Comment by danielgustafsson** [comment]
I don't disagree with adding a profession field, but just because someone marks "journalist" doesn't mean they'll report anything from the event though? What the sponsors want is likely for there to be official press accreditation to IT journalists covering the event.

**Comment by andreasscherbaum** [comment]
Yeah, the idea was that specific entries have a specific meaning (which is shown upfront): "If you select journalist, we can share your contact details with sponsors". Something like that.

Again, needs better thinking how to approach the problem. But we get the "which journalists are at the conference" quite often from marketing departments. If we can ask attendees to provide this information (if they want to), then we help both sides.

**Comment by mhagander** [comment]
If the idea is specifically to identify journalists and this is something the event wants to do it, then this is what the event should do. They specifically ask about who's given journalist passes. This is done by creating a registration *type* for journalists, which is something that has been supported for many many years in the system already.  And has been used successfully for that before.

But I see you agree that it needs more thinking than was done before the issue was created, so I assume that means you're OK with us closing it until there is actually something to work on, in case the already existing solution that has been used before isn't enough?

**Comment by andreasscherbaum** [comment]
Can you just leave this open as discussion ground? I will think more about it and come back. I also plan to talk to sponsors about this.

**Comment by mhagander** [comment]
We have agreed numerous times that this is not a generic open todo list, so I'd rather not. It's one thing with things we're not in agreement with, but having it as a random scratchpad for incomplete ideas makes it even less useful than it already is...

**Comment by dpage** [comment]
I agree that the journalist case would be best served with a dedicated reg type, so unless we want to include profession on badges or do any kind of analytics on it, I don't see any point in adding it. I think even analytics is a stretch; as noted above a predefined list is almost certainly going to exclude a certain percentage of people, and analytics on a free text field doesn't seem helpful.
