### ISSUE TITLE
People on the "Staff" list should automatically bypass the waitlist

### ISSUE THREAD

**Issue by andreasscherbaum** [pgeu/pgeu-system#93]
We (the conference) control who is signed up as Staff. It doesn't make sense to still let anyone from Staff go through the Waitlist loop. Either this person is supposed to be there, or remove it from Staff entirely.

**Comment by andreasscherbaum** [comment]
People are not just randomly added as conference staff, someone with admin rights needs to go in and add the person manually. There is a deeper reason behind this step, and the next step is then to register this person.

> We already have reports to follow up whether the staff expected to be there is actually registered.

So you need to register anyone from staff anyway.

**Comment by andreasscherbaum** [comment]
> they then suddenly change their mind

This rather asks for better communication in the conference team. Again, as you say this has a report and people not signed up and not coming should be removed to satisfy the report.

**Comment by mhagander** [comment]
Right. I'm saying that automatically turning off the built-in safeguards on the system and thereby creating unpredictable situations  should not be a replacement for having proper communications within your system.

**Comment by andreasscherbaum** [comment]
The use case for protecting from missing communication also blocks valid use cases to speed up the process, and adds additional steps (waitlist) to deal with.
